### ISSUE TITLE
New method AbstractHandler::callAction() verursacht PHP Fatal Error bei Neuanlage eines MetaModels

### ISSUE THREAD

**Issue by bopsoid** [contao-community-alliance/dc-general#290] opened 2016-08-13 12:22 UTC
The recently added function callAction() in the file AbstractHandler.php causes with my setup (PHP 5.6) a PHP Fatal Error, as soon as I try to add a new MetaModel:

PHP Fatal error:  Call to a member function setResponse() on null in /var/www/vhosts/???/???/composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/View/ActionHandler/AbstractHandler.php on line 145

This new function is called by the also recently added pasteHandler and then causes the error.

**Comment by cliffparnitzky** [comment] 2016-08-14 16:52
Same probleme is described here: https://github.com/MetaModels/core/issues/1029

**Comment by firekayne** [comment] 2016-08-15 14:46
Same problem here.

**Comment by silenzium** [comment] 2016-08-16 12:12
Same here.

**Comment by zonky2** [comment] 2016-08-16 13:21
o.k. - it´s enough "same here"

**Comment by discordier** [comment] 2016-08-16 20:54
If any of the people writing "me too" and the like would rather provide more information, like a stack trace which is is needed to fix any issue, it would be much better.

Now I am able to reproduce this issue and got the following output:
```
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/PasteHandler.php(63): ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->callAction('create')
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/View/ActionHandler/AbstractHandler.php(54): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\PasteHandler->process()
#2 [internal function]: ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(130): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 system/modules/core/classes/Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#8 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#9 contao/main.php(20): Contao\BackendMain->run()
#10 {main}
```

**Comment by cgpro** [comment] 2016-08-16 21:02
I have the same issue, it worked before the last update. It happens in the filter section too. (logically)

**Comment by discordier** [comment] 2016-08-16 21:23
Should be fixed in beta38 with commit c217064

**Comment by cliffparnitzky** [comment] 2016-08-16 21:23
@discordier The fix looks good. Tested successfully in my environment.

**Comment by cgpro** [comment] 2016-08-16 21:25
Adding a new metamodel works, but not in the filter section in my case.

**Comment by cliffparnitzky** [comment] 2016-08-16 21:28
@cgpro What is "the filter section"???

**Comment by cgpro** [comment] 2016-08-16 21:29
Filter settings, the funnel symbol.

**Comment by cliffparnitzky** [comment] 2016-08-16 21:31
Ok. And the error? In my environment is everything fine.

**Comment by cgpro** [comment] 2016-08-16 21:36
No error message, it happens nothing when I want to add a rule.

**Comment by cgpro** [comment] 2016-08-16 21:46
I made a short screencapture of it:
https://vid.me/BUty

**Comment by cliffparnitzky** [comment] 2016-08-16 21:55
Ah, i understand: "Adding a new attribute setting" to an empty filter setting is the probleme. 

I think this is a new ticket and has nothing to to with the error reported above.

@cgpro Please create a new ticket!

**Comment by cgpro** [comment] 2016-08-16 22:02
Repo mm core or dc-general?

**Comment by cliffparnitzky** [comment] 2016-08-16 22:05
Seems to be a probleme in dc-general (with beta36 i had no probleme).

**Comment by cgpro** [comment] 2016-08-16 22:10
Here is the ticket: #291

**Comment by zonky2** [comment] 2016-08-17 05:59
@discordier: hotfix-38 with MM core a13 works fine! Thanks! pls tagging

**Closed** 2016-08-17 11:21 UTC
Labels: bug
