### ISSUE TITLE
beta32->beta33 Eingabemasken Metamodels im Backend Leer

### ISSUE THREAD

**Issue by amenk** [contao-community-alliance/dc-general#203] opened 2016-03-03 14:12 UTC
_Unser Issue: 13826_

Seite dem Update von beta32->beta33 sind die Eingabemasken der MetaModels im Backend leer.

Es kommt auch ein Warning:

	Warning: array_key_exists() expects parameter 2 to be array, null given in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php on line 779

	#0 [internal function]: __error(2, 'array_key_exist...', '/home/me/local...', 779, Array)
	#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(779): array_key_exists('mm_produkte', NULL)
	#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(402): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->getLegendStates()
	#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(682): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->buildFieldSet(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager), Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Palette\Palette), NULL)
	#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(602): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
	#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(577): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), Object(MetaModels\DcGeneral\Data\Model), NULL, NULL)
	#6 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
	#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(141): call_user_func_array(Array, Array)
	#8 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
	#9 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
	#10 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
	#11 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(130): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
	#12 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
	#13 system/modules/core/classes/Backend.php(406): MetaModels\BackendIntegration\Module->generate()
	#14 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('metamodel_mm_pr...')
	#15 contao/main.php(20): Contao\BackendMain->run()
	#16 {main}

Ist das ein Bug oder muss beim Upgrade etwas beachtet werden?

**Comment by discordier** [comment] 2016-03-03 15:18
Dupe of #185

**Closed by discordier** 2016-03-03 15:18 UTC
Labels: duplicate

**Comment by amenk** [comment] 2016-03-03 15:36
Okay, ist also gefixt in beta34 - aber wie bekomme ich die? Auf Packagist ist nur die beta33 https://packagist.org/packages/contao-community-alliance/dc-general
