### ISSUE TITLE
Support negative filter operations

### ISSUE THREAD

**Issue by tim-bec** [contao-community-alliance/dc-general#43] opened 2014-08-14 13:41 UTC
Orginal: https://github.com/MetaModels/DC_General/issues/116

The used filter syntax of the DcGeneral does not allow negative filters like (```!=``` or ```NOT IN```). I don't know if there is any reason for that.

It would be great if they are also supported.

**Comment by zonky2** [comment] 2016-03-24 13:36
@discordier is duplicate of #20

**Comment by zonky2** [comment] 2016-08-18 13:58
duplicate of #20

**Closed by zonky2** 2016-08-18 13:58 UTC
Labels: duplicate
